### ISSUE TITLE
TypeError: rendered.querySelectorAll is not a function after upgrading to v0.5.0-beta.2 on React

### ISSUE THREAD

**Issue by abjardim** [pagedjs/pagedjs#289]
After upgrading to v0.5.0-beta.2 on my React project, I get the following error when calling previewer.preview:

`Uncaught (in promise) TypeError: rendered.querySelectorAll is not a function
at Chunker.disableRules (pagedjs.js:24215:32)
at Chunker.flow (pagedjs.js:24244:12)
at async Previewer.preview (pagedjs.js:29742:16)
at async preparePrint (PrintExposeTemplate.tsx:121:7)`

The follorwing code snippet worked before with v0.4.3:

`await previewer.preview(
        "<div className="printLayout printExact">${refContent.current.innerHTML}</div>",
        [cssUrl],
        refPrint.current,
)`

I also tried previewing a very simple div instead of my actual content, but that also did not work.

Did something change in the use of the previewer on the latest beta version?
